default:
  occi:
    occi_admin_user: demo
    occi_admin_password: demo

    backends:
      infrastructure:
        compute:
          provider: openstack
          endpoint: ...
          admin_user: demo
          admin_password: demo
        network:
          provider: openstack
          endpoint: ...
          admin_user: demo
          admin_password: demo
        storage:
          provider: openstack
          endpoint: ...
          admin_user: demo
          admin_password: demo

    amqp:
      active: true
      connection_setting:
        host: localhost
        port: 5672
        user: guest
        password: guest
        vhost:
      identifier: amqp.occi.http://141.5.99.83/