default:
  occi:
    occi_admin_user: demo
    occi_admin_password: demo

    backenend:
      infrastructure:
        compute:
          compute_provider: openstack
          compute_endpoint: ...
          compute_admin_user: demo
          compute_admin_password: demo
        network:
          network_provider: openstack
          network_endpoint: ...
          network_admin_user: demo
          network_admin_password: demo
        storage:
          storage_provider: openstack
          storage_endpoint: ...
          storage_admin_user: demo
          storage_admin_password: demo

    amqp:
      active: true
      connection_setting:
        host: localhost
        port: 5672
        user: guest
        password: guest
        vhost:
      identifier: amqp.occi.http://141.5.99.83/